robot=importrobot("rudra_arm\urdf\rudra_arm.urdf");
robot.DataFormat="row";
showdetails(robot);
disp(robot.BaseName);
base=rigidBody("newBase");
jnt=rigidBodyJoint("baseJoint","fixed");
tform = eul2tform([0 0 pi/2]);
setFixedTransform(jnt,tform);
base.Joint=jnt;
cyllinder_radius=0.05;
final_position=[1.6,0.6,0.2];
[x,y,z]=cylinder(cyllinder_radius);
x=x+1.6;
y=y+0.6;
z=z*0.4;
addBody(robot,base,"base_link");
config = homeConfiguration(robot);
q0=config;
ik=inverseKinematics("RigidBodyTree",robot);
endEffector="grip";
weights=[1 1 1 1 1 1];
[a,~]=ik(endEffector,trvec2tform(final_position),weights,q0);
disp(a);
%config (6)=pi/4;
disp(config);
hold on;
surf(x,y,z);
grid on;
view(3);
%show(robot, config, "Frames","off", "PreservePlot", false);
show(robot,a,"PreservePlot",true);
%camorbit(90,0);