robot=loadrobot("fanucLRMate200ib");
showdetails(robot);
config=homeConfiguration(robot);
tform =getTransform(robot,config,'tool0','base');
config(3).JointPosition=pi/2;
disp(config);
disp(tform);
holy=robot.Bodies{2}.Joint;
disp(holy);
center = [0 0 0];
radius = 1;
theta=linspace(0,2*pi,500);
points = center + radius*[cos(theta)' sin(theta)' zeros(size(theta))'];
disp(points);
disp(size(points));
show(robot,randomConfiguration(robot));