function robot = robotBuildforCodegen(dataFormat)
%robotBuildforCodegen Create rigidBodyTree for the robot model
%   ROBOT = robotBuildforCodegen(DATAFORMAT) constructs a rigidBodyTree, ROBOT, and sets the
%   data format to DATAFORMAT. The possible values of DATAFORMAT are 
%   'struct', 'column' and 'row'. The default value is 'row', which 
%   matches the data format of the rigidbodytree object used to generate 
%   this function.

%   Auto-generated by MATLAB on 09-Feb-2026 00:13:46

%#codegen

narginchk(0,1);
if ~nargin==1
dataFormat='row';
end
robot = rigidBodyTree('MaxNumBodies', 3, 'DataFormat', dataFormat);
robot.Gravity = [                     0,                      0,                      0];
robot.BaseName = 'base';


% Add body, 'Body1', and joint, 'jnt1'
bodyName = 'Body1';
bodyMass =                      1;
bodyCoM = [                     0,                      0,                      0];
bodyInertia = [                     1,                      1,                      1,                      0,                      0,                      0];
parentName = 'base';
jointName = 'jnt1';
jointType = 'revolute';
T_Joint_to_Parent = [                     1,                      0,                      0,                      0; ...
                                          0,                      1,                      0,                      0; ...
                                          0,                      0,                      1,                      0; ...
                                          0,                      0,                      0,                      1];

joint = rigidBodyJoint(jointName, jointType);
joint.setFixedTransform(T_Joint_to_Parent);
jointAxis = [                     0,                      0,                      1];
jointPositionLimits = [    -3.141592653589793,      3.141592653589793];
jointHomePosition =                      0;
joint.PositionLimits = jointPositionLimits;
joint.JointAxis = jointAxis;
joint.HomePosition = jointHomePosition;
body = rigidBody(bodyName, "MaxNumCollisions", 0);

body.Joint = joint;
body.Mass = bodyMass;
body.CenterOfMass = bodyCoM;
body.Inertia = bodyInertia;
robot.addBody(body, parentName);


% Add body, 'body2', and joint, 'jnt2'
bodyName = 'body2';
bodyMass =                      1;
bodyCoM = [                     0,                      0,                      0];
bodyInertia = [                     1,                      1,                      1,                      0,                      0,                      0];
parentName = 'Body1';
jointName = 'jnt2';
jointType = 'revolute';
T_Joint_to_Parent = [                     1,                      0,                      0,                    0.3; ...
                                          0,                      1,                      0,                      0; ...
                                          0,                      0,                      1,                      0; ...
                                          0,                      0,                      0,                      1];

joint = rigidBodyJoint(jointName, jointType);
joint.setFixedTransform(T_Joint_to_Parent);
jointAxis = [                     0,                      0,                      1];
jointPositionLimits = [    -3.141592653589793,      3.141592653589793];
jointHomePosition =                      0;
joint.PositionLimits = jointPositionLimits;
joint.JointAxis = jointAxis;
joint.HomePosition = jointHomePosition;
body = rigidBody(bodyName, "MaxNumCollisions", 0);

body.Joint = joint;
body.Mass = bodyMass;
body.CenterOfMass = bodyCoM;
body.Inertia = bodyInertia;
robot.addBody(body, parentName);


% Add body, 'tool_tip', and joint, 'jnt3'
bodyName = 'tool_tip';
bodyMass =                      1;
bodyCoM = [                     0,                      0,                      0];
bodyInertia = [                     1,                      1,                      1,                      0,                      0,                      0];
parentName = 'body2';
jointName = 'jnt3';
jointType = 'fixed';
T_Joint_to_Parent = [                     1,                      0,                      0,                    0.3; ...
                                          0,                      1,                      0,                      0; ...
                                          0,                      0,                      1,                      0; ...
                                          0,                      0,                      0,                      1];

joint = rigidBodyJoint(jointName, jointType);
joint.setFixedTransform(T_Joint_to_Parent);
body = rigidBody(bodyName, "MaxNumCollisions", 0);

body.Joint = joint;
body.Mass = bodyMass;
body.CenterOfMass = bodyCoM;
body.Inertia = bodyInertia;
robot.addBody(body, parentName);


