function robot = rmrcRobot(dataFormat)
%rmrcRobot Create rigidBodyTree for the robot model
%   ROBOT = rmrcRobot(DATAFORMAT) constructs a rigidBodyTree, ROBOT, and sets the
%   data format to DATAFORMAT. The possible values of DATAFORMAT are 
%   'struct', 'column' and 'row'. The default value is 'row', which 
%   matches the data format of the rigidbodytree object used to generate 
%   this function.

%   Auto-generated by MATLAB on 07-Mar-2026 02:10:04

%#codegen

narginchk(0,1);
if nargin<1
    dataFormat='row';
end
robot = rigidBodyTree('MaxNumBodies', 8, 'DataFormat', dataFormat);
robot.Gravity = [                     0,                      0,                      0];
robot.BaseName = 'base_link';


% Add body, 'base', and joint, 'base_link-base'
bodyName = 'base';
bodyMass =                      0;
bodyCoM = [                     0,                      0,                      0];
bodyInertia = [                     0,                      0,                      0,                      0,                      0,                      0];
parentName = 'base_link';
jointName = 'base_link-base';
jointType = 'fixed';
T_Joint_to_Parent = [                     1,                      0,                      0,                      0; ...
                                          0,                      1,                      0,                      0; ...
                                          0,                      0,                      1,                      0; ...
                                          0,                      0,                      0,                      1];

joint = rigidBodyJoint(jointName, jointType);
joint.setFixedTransform(T_Joint_to_Parent);
body = rigidBody(bodyName, "MaxNumCollisions", 0);

body.Joint = joint;
body.Mass = bodyMass;
body.CenterOfMass = bodyCoM;
body.Inertia = bodyInertia;
robot.addBody(body, parentName);


% Add body, 'link_1', and joint, 'joint_1'
bodyName = 'link_1';
bodyMass =                  3.067;
bodyCoM = [              9.77e-05,               -0.00012,                0.23841];
bodyInertia = [       0.1885437634475,     0.1887303485581045,    0.01045337344020443,        0.0001070848164,      -9.4574979019e-05,      -1.2821942492e-05];
parentName = 'base_link';
jointName = 'joint_1';
jointType = 'revolute';
T_Joint_to_Parent = [                     1,                      0,                      0,                      0; ...
                                          0,                      1,                      0,                      0; ...
                                          0,                      0,                      1,                      0; ...
                                          0,                      0,                      0,                      1];

joint = rigidBodyJoint(jointName, jointType);
joint.setFixedTransform(T_Joint_to_Parent);
jointAxis = [                     0,                      0,                      1];
jointPositionLimits = [              -2.87979,                2.87979];
jointHomePosition =                      0;
joint.PositionLimits = jointPositionLimits;
joint.JointAxis = jointAxis;
joint.HomePosition = jointHomePosition;
body = rigidBody(bodyName, "MaxNumCollisions", 1);

body.Joint = joint;
body.Mass = bodyMass;
body.CenterOfMass = bodyCoM;
body.Inertia = bodyInertia;
robot.addBody(body, parentName);


% Add body, 'link_2', and joint, 'joint_2'
bodyName = 'link_2';
bodyMass =                  3.909;
bodyCoM = [               0.00078,               -0.00212,                0.10124];
bodyInertia = [        0.100394111088,         0.081636820714,        0.0259747468452,  0.0003340139791999999,       -0.0002514420848,         1.62982324e-05];
parentName = 'link_1';
jointName = 'joint_2';
jointType = 'revolute';
T_Joint_to_Parent = [                     1,                      0,                      0,                      0; ...
                                          0,                      1,                      0,                      0; ...
                                          0,                      0,                      1,                   0.29; ...
                                          0,                      0,                      0,                      1];

joint = rigidBodyJoint(jointName, jointType);
joint.setFixedTransform(T_Joint_to_Parent);
jointAxis = [                     0,                      1,                      0];
jointPositionLimits = [              -1.91986,                1.91986];
jointHomePosition =                      0;
joint.PositionLimits = jointPositionLimits;
joint.JointAxis = jointAxis;
joint.HomePosition = jointHomePosition;
body = rigidBody(bodyName, "MaxNumCollisions", 1);

body.Joint = joint;
body.Mass = bodyMass;
body.CenterOfMass = bodyCoM;
body.Inertia = bodyInertia;
robot.addBody(body, parentName);


% Add body, 'link_3', and joint, 'joint_3'
bodyName = 'link_3';
bodyMass =                  2.944;
bodyCoM = [               0.02281,                0.00106,                0.05791];
bodyInertia = [       0.0182322723648,        0.0281176562048,        0.0142334595968,       -0.0003629432624,  -0.002459969382400001,       -0.0001513362984];
parentName = 'link_2';
jointName = 'joint_3';
jointType = 'revolute';
T_Joint_to_Parent = [                     1,                      0,                      0,                      0; ...
                                          0,                      1,                      0,                      0; ...
                                          0,                      0,                      1,                   0.27; ...
                                          0,                      0,                      0,                      1];

joint = rigidBodyJoint(jointName, jointType);
joint.setFixedTransform(T_Joint_to_Parent);
jointAxis = [                     0,                      1,                      0];
jointPositionLimits = [              -1.91986,                1.22173];
jointHomePosition =                      0;
joint.PositionLimits = jointPositionLimits;
joint.JointAxis = jointAxis;
joint.HomePosition = jointHomePosition;
body = rigidBody(bodyName, "MaxNumCollisions", 1);

body.Joint = joint;
body.Mass = bodyMass;
body.CenterOfMass = bodyCoM;
body.Inertia = bodyInertia;
robot.addBody(body, parentName);


% Add body, 'link_4', and joint, 'joint_4'
bodyName = 'link_4';
bodyMass =                  1.328;
bodyCoM = [                0.2247,                0.00015,                0.00041];
bodyInertia = [       0.0028468631168,    0.07106452275680002,    0.07230436940000001,          1.3051928e-05,        -0.000138779656,          -6.603674e-05];
parentName = 'link_3';
jointName = 'joint_4';
jointType = 'revolute';
T_Joint_to_Parent = [                     1,                      0,                      0,                      0; ...
                                          0,                      1,                      0,                      0; ...
                                          0,                      0,                      1,    0.07000000000000001; ...
                                          0,                      0,                      0,                      1];

joint = rigidBodyJoint(jointName, jointType);
joint.setFixedTransform(T_Joint_to_Parent);
jointAxis = [                     1,                      0,                      0];
jointPositionLimits = [              -2.79253,                2.79253];
jointHomePosition =                      0;
joint.PositionLimits = jointPositionLimits;
joint.JointAxis = jointAxis;
joint.HomePosition = jointHomePosition;
body = rigidBody(bodyName, "MaxNumCollisions", 1);

body.Joint = joint;
body.Mass = bodyMass;
body.CenterOfMass = bodyCoM;
body.Inertia = bodyInertia;
robot.addBody(body, parentName);


% Add body, 'link_5', and joint, 'joint_5'
bodyName = 'link_5';
bodyMass =                  0.546;
bodyCoM = [              -0.00109,               3.68e-05,  6.219999999999999e-05];
bodyInertia = [   0.00040489385180168,  0.0008934758149866399,    0.00081611744201504,       -1.642897216e-08,         8.83822708e-07,        1.641331152e-06];
parentName = 'link_4';
jointName = 'joint_5';
jointType = 'revolute';
T_Joint_to_Parent = [                     1,                      0,                      0,                  0.302; ...
                                          0,                      1,                      0,                      0; ...
                                          0,                      0,                      1,                      0; ...
                                          0,                      0,                      0,                      1];

joint = rigidBodyJoint(jointName, jointType);
joint.setFixedTransform(T_Joint_to_Parent);
jointAxis = [                     0,                      1,                      0];
jointPositionLimits = [             -2.094395,               2.094395];
jointHomePosition =                      0;
joint.PositionLimits = jointPositionLimits;
joint.JointAxis = jointAxis;
joint.HomePosition = jointHomePosition;
body = rigidBody(bodyName, "MaxNumCollisions", 1);

body.Joint = joint;
body.Mass = bodyMass;
body.CenterOfMass = bodyCoM;
body.Inertia = bodyInertia;
robot.addBody(body, parentName);


% Add body, 'link_6', and joint, 'joint_6'
bodyName = 'link_6';
bodyMass =                  0.137;
bodyCoM = [              -0.00706,               -0.00017,              -1.32e-06];
bodyInertia = [  0.001000003959538709,   0.001006828573438709,        0.0010068325325,           -3.07428e-11,         -1.2767304e-09,          -1.644274e-07];
parentName = 'link_5';
jointName = 'joint_6';
jointType = 'revolute';
T_Joint_to_Parent = [                     1,                      0,                      0,    0.07199999999999999; ...
                                          0,                      1,                      0,                      0; ...
                                          0,                      0,                      1,                      0; ...
                                          0,                      0,                      0,                      1];

joint = rigidBodyJoint(jointName, jointType);
joint.setFixedTransform(T_Joint_to_Parent);
jointAxis = [                     1,                      0,                      0];
jointPositionLimits = [              -6.98132,                6.98132];
jointHomePosition =                      0;
joint.PositionLimits = jointPositionLimits;
joint.JointAxis = jointAxis;
joint.HomePosition = jointHomePosition;
body = rigidBody(bodyName, "MaxNumCollisions", 1);

body.Joint = joint;
body.Mass = bodyMass;
body.CenterOfMass = bodyCoM;
body.Inertia = bodyInertia;
robot.addBody(body, parentName);


% Add body, 'tool0', and joint, 'joint6-tool0'
bodyName = 'tool0';
bodyMass =                      0;
bodyCoM = [                     0,                      0,                      0];
bodyInertia = [                     0,                      0,                      0,                      0,                      0,                      0];
parentName = 'link_6';
jointName = 'joint6-tool0';
jointType = 'fixed';
T_Joint_to_Parent = [                     1,                      0,                      0,                      0; ...
                                          0,                      1,                      0,                      0; ...
                                          0,                      0,                      1,                      0; ...
                                          0,                      0,                      0,                      1];

joint = rigidBodyJoint(jointName, jointType);
joint.setFixedTransform(T_Joint_to_Parent);
body = rigidBody(bodyName, "MaxNumCollisions", 0);

body.Joint = joint;
body.Mass = bodyMass;
body.CenterOfMass = bodyCoM;
body.Inertia = bodyInertia;
robot.addBody(body, parentName);


